version: '3'

services:
  am_fun_inc_app:
    user: app
    build:
      context: .
      args:
        USER_ID: ${USER_ID}
    depends_on:
      - am_fun_inc_db
    ports:
      - "8337:8337"
    volumes:
      - .:/app:rw
    environment:
      - APP_ENV=dev

  am_fun_inc_db:
    image: postgres
    container_name: am_fun_inc_db
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: am_fun_inc
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
